### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by aaahrens** [jsonresume/theme-manager#37]
Hey guys, pretty sure your site is down for all subdomains. themes.X and registry.X are both giving 502s.

**Comment by thomasdavis** [comment]
On it, thanks.

On 22 Oct 2017 13:34, "Adam Ahrens" <notifications@github.com> wrote:

Hey guys, pretty sure your site is down for all subdomains. themes.X and
registry.X are both giving 502s.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jsonresume/theme-manager/issues/37>, or mute the thread

**Comment by hjhart** [comment]
This still appears to be down. Has it been down since October?

**Comment by thomasdavis** [comment]
This has been resolved, reference https://github.com/jsonresume/registry-server/issues/98

**Comment by mcarbonneaux** [comment]
Down again?
